# Pytorch 여러 함수

In [2]:
import torch

In [3]:
# 정규분포를 따르는 난수로 이루어진 텐서 생성, 평균0 표준편차1을 기준으로 함
a=torch.randn(2,3)
print(a)
# 0~1에서 랜덤 수로 채워진 텐서
b=torch.rand(2,4)
print(b)

tensor([[-0.4919, -0.1856,  2.0861],
        [ 1.6132,  0.5517,  1.3681]])
tensor([[0.5525, 0.8091, 0.6071, 0.9934],
        [0.6160, 0.1591, 0.0927, 0.8358]])


In [5]:
a=torch.randn(4,4)
print(a)
print(torch.abs(a)) # 절대값, 음수->양수
print(torch.sqrt(a)) # 제곱근
print(torch.sqrt(torch.abs(a)))
print(torch.exp(a)) # e^x(e=2.71828)
print(torch.log(torch.abs(a)))
print(torch.log(torch.exp(torch.tensor(1))))
print(torch.log10(torch.tensor(10)))
print(torch.log2(torch.tensor(2)))
print(torch.round(a)) # 반올림
print(torch.round(a, decimals=2)) # 소수점 둘째자리까지
print(torch.floor(a)) # 내림
print(torch.ceil(a)) # 오름차순

tensor([[ 0.6546,  1.0381,  1.9199, -1.4582],
        [ 0.2243, -0.7494,  1.2812,  0.7600],
        [-0.8572, -0.9383, -0.6011, -1.0509],
        [ 1.7511,  2.0035, -0.7939, -0.0771]])
tensor([[0.6546, 1.0381, 1.9199, 1.4582],
        [0.2243, 0.7494, 1.2812, 0.7600],
        [0.8572, 0.9383, 0.6011, 1.0509],
        [1.7511, 2.0035, 0.7939, 0.0771]])
tensor([[0.8091, 1.0189, 1.3856,    nan],
        [0.4736,    nan, 1.1319, 0.8718],
        [   nan,    nan,    nan,    nan],
        [1.3233, 1.4155,    nan,    nan]])
tensor([[0.8091, 1.0189, 1.3856, 1.2076],
        [0.4736, 0.8657, 1.1319, 0.8718],
        [0.9258, 0.9687, 0.7753, 1.0251],
        [1.3233, 1.4155, 0.8910, 0.2777]])
tensor([[1.9244, 2.8238, 6.8202, 0.2327],
        [1.2515, 0.4726, 3.6009, 2.1384],
        [0.4244, 0.3913, 0.5482, 0.3496],
        [5.7607, 7.4152, 0.4521, 0.9258]])
tensor([[-0.4237,  0.0374,  0.6523,  0.3772],
        [-1.4947, -0.2885,  0.2478, -0.2744],
        [-0.1541, -0.0637, -0.5090,  0.0496],
 

In [6]:
print(torch.sin(torch.tensor(torch.pi/6)))
print(torch.cos(torch.tensor(torch.pi/3)))
print(torch.tan(torch.tensor(torch.pi/4)))
print(torch.tanh(torch.tensor(-10)))

tensor(0.5000)
tensor(0.5000)
tensor(1.)
tensor(-1.)


In [7]:
a=torch.randn(6,1)
print(a)
a_sorted=torch.sort(a,dim=0) # 정렬/dim이 0이면 열(세로), 1이면 행(가로)
print(a_sorted)
b_sorted=torch.sort(a,dim=0,descending=False)
print(b_sorted)

tensor([[ 0.4241],
        [ 1.5312],
        [ 0.9850],
        [ 0.5133],
        [-0.8611],
        [ 0.6019]])
torch.return_types.sort(
values=tensor([[-0.8611],
        [ 0.4241],
        [ 0.5133],
        [ 0.6019],
        [ 0.9850],
        [ 1.5312]]),
indices=tensor([[4],
        [0],
        [3],
        [5],
        [2],
        [1]]))
torch.return_types.sort(
values=tensor([[-0.8611],
        [ 0.4241],
        [ 0.5133],
        [ 0.6019],
        [ 0.9850],
        [ 1.5312]]),
indices=tensor([[4],
        [0],
        [3],
        [5],
        [2],
        [1]]))


In [8]:
A=torch.randn(6,4)
print(A)
print(torch.sum(A,dim=1))
print(torch.sum(A,dim=0))
print(torch.mean(A)) # 평균
print(torch.mean(A, dim=1, keepdims=True)) # keepdims가 True면 차원 유지
print(torch.std(A)) # 표준편차

tensor([[ 0.8841, -1.5984,  0.6681,  0.1126],
        [ 0.6561,  0.7397, -0.3290, -1.5749],
        [ 1.0088, -0.8891, -0.3354,  0.7296],
        [ 1.2977,  0.2822,  1.3918,  1.2230],
        [-0.1466,  1.5379, -0.3552, -0.0596],
        [ 0.0830,  0.2248, -0.9805, -0.4623]])
tensor([ 0.0664, -0.5081,  0.5138,  4.1947,  0.9765, -1.1349])
tensor([ 3.7832,  0.2971,  0.0598, -0.0317])
tensor(0.1712)
tensor([[ 0.0166],
        [-0.1270],
        [ 0.1285],
        [ 1.0487],
        [ 0.2441],
        [-0.2837]])
tensor(0.8860)


In [9]:
A=torch.randint(1,5,size=(12,)) # 1부터 5미만 12개 정수
print(A)
print(A.shape)
B=A.reshape(2,1,6)
print(B)
print(B.ndim)

tensor([4, 1, 2, 2, 1, 1, 3, 2, 4, 1, 3, 1])
torch.Size([12])
tensor([[[4, 1, 2, 2, 1, 1]],

        [[3, 2, 4, 1, 3, 1]]])
3


In [10]:
a=torch.tensor([1,2,3])
b=torch.tensor([4,5,5])
print(torch.sum(a*b))

tensor(29)
