# Pytorch

In [ ]:
import torch

In [ ]:
a=torch.tensor([1,2,3,4])
print(a)
print(type(a))
print(a.dtype)
print(a.shape)

tensor([1, 2, 3, 4])
<class 'torch.Tensor'>
torch.int64
torch.Size([4])


In [ ]:
A=torch.tensor([[1,2,3],[4,5,6]])
print(A)
print(A.ndim)
print(A.numel())

tensor([[1, 2, 3],
        [4, 5, 6]])
2
6


In [ ]:
print(torch.zeros(5))
print(torch.zeros_like(A))
print(torch.ones(5))
print(torch.zeros(3,6))
print(torch.arange(1,9,2)) # range랑 똑같은데 tensor로 만들어줌
print(torch.arange(1,2,0.1)) # 소수점도 가능
print(torch.linspace(0,1,10)) # 0부터 1까지 10개

tensor([0., 0., 0., 0., 0.])
tensor([[0, 0, 0],
        [0, 0, 0]])
tensor([1., 1., 1., 1., 1.])
tensor([[0., 0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0., 0.]])
tensor([1, 3, 5, 7])
tensor([1.0000, 1.1000, 1.2000, 1.3000, 1.4000, 1.5000, 1.6000, 1.7000, 1.8000,
        1.9000])
tensor([0.0000, 0.1111, 0.2222, 0.3333, 0.4444, 0.5556, 0.6667, 0.7778, 0.8889,
        1.0000])


In [ ]:
A=torch.tensor([[1,2,3],[4,5,6]])
B=torch.tensor([[7,8,9],[10,11,12]])
print(A+B)
print(A-B)
print(A*B) # 성분끼리 곱
print(A**2)
print(A@B) # 행렬 곱

tensor([[ 8, 10, 12],
        [14, 16, 18]])
tensor([[-6, -6, -6],
        [-6, -6, -6]])
tensor([[ 7, 16, 27],
        [40, 55, 72]])
tensor([[ 1,  4,  9],
        [16, 25, 36]])


In [ ]:
import torch as t
a=t.tensor([1,2,3])
print(a)
print(t.zeros_like(a))

tensor([1, 2, 3])
tensor([0, 0, 0])


In [ ]:
a=t.tensor([1,2,3,4,5,6,7,8])
print(a[2])
print(a[0:3])
print(a[:])
print(a[3:])

tensor(3)
tensor([1, 2, 3])
tensor([1, 2, 3, 4, 5, 6, 7, 8])
tensor([4, 5, 6, 7, 8])


In [ ]:
A=t.tensor([[1,2,3,4],[5,6,7,8]])
print(A[0][2])
print(A[1,:]) # 1행 전부
print(A[:,2]) # 전부 2열

tensor(3)
tensor([5, 6, 7, 8])
tensor([3, 7])


In [ ]:
b=t.tensor([[[1,2,3,4],[4,5,6,7],[7,8,9,10]], [[10,11,12,13],[13,14,15,16],[16,17,18,19]]])
print(b)
print(b.shape) # 3*4짜리가 2개
print(b[0,2,3])

tensor([[[ 1,  2,  3,  4],
         [ 4,  5,  6,  7],
         [ 7,  8,  9, 10]],

        [[10, 11, 12, 13],
         [13, 14, 15, 16],
         [16, 17, 18, 19]]])
torch.Size([2, 3, 4])
tensor(10)


In [ ]:
# boolean 인덱싱
a=[1,2,3,4,5]
print(a==3)
A=t.tensor([[1,2,3,4],[5,6,7,3]])
print(A==3) # 리스트와 달리 각 성분에 대해 비교해줌
# A[] <- 인덱싱할거다
print(A[A==3]) # true, false가 담긴 행렬로 인덱싱 가능
A[A==3]=100 # 3을 100으로 바꿈
print(A)
A=t.tensor([[1,2],[3,4],[5,6],[7,8]])
B=t.tensor([True, False, True, False])
print(A[B,:])

False
tensor([[False, False,  True, False],
        [False, False, False,  True]])
tensor([3, 3])
tensor([[  1,   2, 100,   4],
        [  5,   6,   7, 100]])
tensor([[1, 2],
        [5, 6]])


In [ ]:
# tensor로 인덱싱
b=t.tensor([1,2,3,4,5])
print(b[3])
print(b[t.tensor([2,3,4])])
print(b[t.tensor([[2,2,2],[3,3,3]])]) # 인덱싱된 애들로 2행3열짜리 행렬 만든다

tensor(4)
tensor([3, 4, 5])
tensor([[3, 3, 3],
        [4, 4, 4]])


In [ ]:
c=t.tensor([[1,2],[3,4],[5,6],[7,8]])
print(c.shape)
# 몇번째 행, 열이냐
print(c[0][1])

torch.Size([4, 2])
tensor(2)
