In [46]:
import torch

In [ ]:
a=torch.tensor([1,2,3,4])
print(a)
print(type(a))
print(a.dtype)
print(a.shape)

tensor([1, 2, 3, 4])
<class 'torch.Tensor'>
torch.int64
torch.Size([4])


In [ ]:
A=torch.tensor([[1,2,3],[4,5,6]])
print(A)
print(A.ndim)
print(A.numel())

tensor([[1, 2, 3],
        [4, 5, 6]])
2
6


In [ ]:
print(torch.zeros(5))
print(torch.zeros_like(A))
print(torch.ones(5))
print(torch.zeros(3,6))
print(torch.arange(1,9,2)) # range랑 똑같은데 tensor로 만들어줌
print(torch.arange(1,2,0.1)) # 소수점도 가능
print(torch.linspace(0,1,10)) # 0부터 1까지 10개

tensor([0., 0., 0., 0., 0.])
tensor([[0, 0, 0],
        [0, 0, 0]])
tensor([1., 1., 1., 1., 1.])
tensor([[0., 0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0., 0.]])
tensor([1, 3, 5, 7])
tensor([1.0000, 1.1000, 1.2000, 1.3000, 1.4000, 1.5000, 1.6000, 1.7000, 1.8000,
        1.9000])
tensor([0.0000, 0.1111, 0.2222, 0.3333, 0.4444, 0.5556, 0.6667, 0.7778, 0.8889,
        1.0000])


In [ ]:
A=torch.tensor([[1,2,3],[4,5,6]])
B=torch.tensor([[7,8,9],[10,11,12]])
print(A+B)
print(A-B)
print(A*B) # 성분끼리 곱
print(A**2)
print(A@B) # 행렬 곱

tensor([[ 8, 10, 12],
        [14, 16, 18]])
tensor([[-6, -6, -6],
        [-6, -6, -6]])
tensor([[ 7, 16, 27],
        [40, 55, 72]])
tensor([[ 1,  4,  9],
        [16, 25, 36]])


In [1]:
import torch as t
a=t.tensor([1,2,3])
print(a)
print(t.zeros_like(a))

tensor([1, 2, 3])
tensor([0, 0, 0])


In [7]:
a=t.tensor([1,2,3,4,5,6,7,8])
print(a[2])
print(a[0:3])
print(a[:])
print(a[3:])

tensor(3)
tensor([1, 2, 3])
tensor([1, 2, 3, 4, 5, 6, 7, 8])
tensor([4, 5, 6, 7, 8])


In [13]:
A=t.tensor([[1,2,3,4],[5,6,7,8]])
print(A[0][2])
print(A[1,:]) # 1행 전부
print(A[:,2]) # 전부 2열

tensor(3)
tensor([5, 6, 7, 8])
tensor([3, 7])


In [19]:
b=t.tensor([[[1,2,3,4],[4,5,6,7],[7,8,9,10]], [[10,11,12,13],[13,14,15,16],[16,17,18,19]]])
print(b)
print(b.shape) # 3*4짜리가 2개
print(b[0,2,3])

tensor([[[ 1,  2,  3,  4],
         [ 4,  5,  6,  7],
         [ 7,  8,  9, 10]],

        [[10, 11, 12, 13],
         [13, 14, 15, 16],
         [16, 17, 18, 19]]])
torch.Size([2, 3, 4])
tensor(10)


In [33]:
# boolean 인덱싱
a=[1,2,3,4,5]
print(a==3)
A=t.tensor([[1,2,3,4],[5,6,7,3]])
print(A==3) # 리스트와 달리 각 성분에 대해 비교해줌
# A[] <- 인덱싱할거다
print(A[A==3]) # true, false가 담긴 행렬로 인덱싱 가능
A[A==3]=100 # 3을 100으로 바꿈
print(A)
A=t.tensor([[1,2],[3,4],[5,6],[7,8]])
B=t.tensor([True, False, True, False])
print(A[B,:])

False
tensor([[False, False,  True, False],
        [False, False, False,  True]])
tensor([3, 3])
tensor([[  1,   2, 100,   4],
        [  5,   6,   7, 100]])
tensor([[1, 2],
        [5, 6]])


In [43]:
# tensor로 인덱싱
b=t.tensor([1,2,3,4,5])
print(b[3])
print(b[t.tensor([2,3,4])])
print(b[t.tensor([[2,2,2],[3,3,3]])]) # 인덱싱된 애들로 2행3열짜리 행렬 만든다

tensor(4)
tensor([3, 4, 5])
tensor([[3, 3, 3],
        [4, 4, 4]])


In [45]:
c=t.tensor([[1,2],[3,4],[5,6],[7,8]])
print(c.shape)
# 몇번째 행, 열이냐
print(c[0][1])

torch.Size([4, 2])
tensor(2)


# pytorch 여러 함수

In [50]:
# 정규분포를 따르는 난수로 이루어진 텐서 생성, 평균0 표준편차1을 기준으로 함
a=t.randn(2,3)
print(a)
# 0~1에서 랜덤 수로 채워진 텐서
b=t.rand(2,4)
print(b)

tensor([[ 1.9574,  0.7488, -0.6421],
        [ 0.5079,  1.7208,  2.2676]])
tensor([[0.9340, 0.8464, 0.3530, 0.0458],
        [0.6545, 0.8770, 0.4946, 0.6631]])


In [65]:
a=t.randn(4,4)
print(a)
print(torch.abs(a)) # 절대값, 음수->양수
print(torch.sqrt(a)) # 제곱근
print(torch.sqrt(torch.abs(a)))
print(torch.exp(a)) # e^x(e=2.71828)
print(torch.log(torch.abs(a)))
print(torch.log(torch.exp(torch.tensor(1))))
print(torch.log10(torch.tensor(10)))
print(torch.log2(torch.tensor(2)))
print(torch.round(a)) # 반올림
print(torch.round(a, decimals=2)) # 소수점 둘째자리까지
print(torch.floor(a)) # 내림
print(torch.ceil(a)) # 오름차순

tensor([[ 1.4843, -0.6002,  0.2418,  2.4070],
        [-0.7765,  1.5086, -0.7295, -1.1015],
        [-1.3980,  2.3288, -1.4831, -0.3121],
        [-1.0080,  0.2839, -3.8964,  0.3684]])
tensor([[1.4843, 0.6002, 0.2418, 2.4070],
        [0.7765, 1.5086, 0.7295, 1.1015],
        [1.3980, 2.3288, 1.4831, 0.3121],
        [1.0080, 0.2839, 3.8964, 0.3684]])
tensor([[1.2183,    nan, 0.4917, 1.5515],
        [   nan, 1.2283,    nan,    nan],
        [   nan, 1.5261,    nan,    nan],
        [   nan, 0.5328,    nan, 0.6069]])
tensor([[1.2183, 0.7747, 0.4917, 1.5515],
        [0.8812, 1.2283, 0.8541, 1.0495],
        [1.1824, 1.5261, 1.2178, 0.5586],
        [1.0040, 0.5328, 1.9739, 0.6069]])
tensor([[ 4.4120,  0.5487,  1.2735, 11.1011],
        [ 0.4600,  4.5205,  0.4822,  0.3324],
        [ 0.2471, 10.2660,  0.2269,  0.7319],
        [ 0.3649,  1.3283,  0.0203,  1.4454]])
tensor([[ 0.3950, -0.5105, -1.4197,  0.8784],
        [-0.2530,  0.4112, -0.3155,  0.0966],
        [ 0.3350,  0.8454,  0.3

In [66]:
print(torch.sin(torch.tensor(torch.pi/6)))
print(torch.cos(torch.tensor(torch.pi/3)))
print(torch.tan(torch.tensor(torch.pi/4)))
print(torch.tanh(torch.tensor(-10)))

tensor(0.5000)
tensor(0.5000)
tensor(1.)
tensor(-1.)


In [71]:
a=torch.randn(6,1)
print(a)
a_sorted=torch.sort(a,dim=0) # 정렬/dim이 0이면 열(세로), 1이면 행(가로)
print(a_sorted)
b_sorted=torch.sort(a,dim=0,descending=False)
print(b_sorted)

tensor([[ 0.8206],
        [ 0.0299],
        [-1.7397],
        [-0.0909],
        [ 1.5816],
        [ 1.1912]])
torch.return_types.sort(
values=tensor([[-1.7397],
        [-0.0909],
        [ 0.0299],
        [ 0.8206],
        [ 1.1912],
        [ 1.5816]]),
indices=tensor([[2],
        [3],
        [1],
        [0],
        [5],
        [4]]))
torch.return_types.sort(
values=tensor([[-1.7397],
        [-0.0909],
        [ 0.0299],
        [ 0.8206],
        [ 1.1912],
        [ 1.5816]]),
indices=tensor([[2],
        [3],
        [1],
        [0],
        [5],
        [4]]))


In [77]:
A=torch.randn(6,4)
print(A)
print(torch.sum(A,dim=1))
print(torch.sum(A,dim=0))
print(torch.mean(A)) # 평균
print(torch.mean(A, dim=1, keepdims=True)) # keepdims가 True면 차원 유지
print(torch.std(A)) # 표준편차

tensor([[-0.8838,  0.3302, -0.1192, -0.9058],
        [-1.1565,  0.7692,  0.2361, -0.9387],
        [-0.2006, -0.7104,  0.5995, -0.6276],
        [ 0.5241, -0.3924,  0.7263, -0.3366],
        [-0.9048,  0.5844, -1.7413,  1.5194],
        [ 0.1814, -0.9473,  1.7875,  0.8192]])
tensor([-1.5785, -1.0899, -0.9391,  0.5214, -0.5424,  1.8407])
tensor([-2.4401, -0.3663,  1.4889, -0.4702])
tensor(-0.0745)
tensor([[-0.3946],
        [-0.2725],
        [-0.2348],
        [ 0.1304],
        [-0.1356],
        [ 0.4602]])
tensor(0.8877)


In [86]:
A=torch.randint(1,5,size=(12,)) # 1부터 5미만 12개 정수
print(A)
print(A.shape)
B=A.reshape(2,1,6)
print(B)
print(B.ndim)

tensor([1, 3, 1, 3, 4, 2, 1, 1, 4, 4, 1, 1])
torch.Size([12])
tensor([[[1, 3, 1, 3, 4, 2]],

        [[1, 1, 4, 4, 1, 1]]])
3


In [89]:
a=torch.tensor([1,2,3])
b=torch.tensor([4,5,5])
print(torch.sum(a*b))

tensor(29)
