In [2]:
import torch
from torch import nn

In [7]:
x=torch.tensor([1.])
model=nn.Linear(1,1) # 입력 node 1개, 출력 node 1개인 layer 만듦
print(model.weight) # 가중치
print(model.bias)
y=model(x)
print(y)
y=x@model.weight+model.bias # @:행렬연산, *:요소끼리 연산
print(y)

Parameter containing:
tensor([[-0.8210]], requires_grad=True)
Parameter containing:
tensor([0.9750], requires_grad=True)
tensor([0.1540], grad_fn=<ViewBackward0>)
tensor([0.1540], grad_fn=<AddBackward0>)


In [11]:
fc1=nn.Linear(1,3) # fully-connected
fc2=nn.Linear(3,1)

print(fc1.weight)
print(fc1.bias)
print(fc2.weight)
print(fc2.bias)

x=torch.tensor([1.])
x=fc1(x)
print(x)
x=fc2(x)
print(x)

y=(x@fc1.weight.T+fc1.bias)@fc2.weight.T+fc2.bias
print(y)
# 노드 하나가 곧 한개의 채널임
# 따라서 데이터 여러개를 통과시키고 싶다면 개x채 형태로 줘야 함
# why T? weight도 개x채 형태로 만들기 위함
# 일단, weight shape 개x채에서 채는 무조건 무조건 앞에 거 채널 개수와 맞추기
# ex) nn.Linear(2,3)이면 앞에거 채널 개수는 2, 따라서 ?x2 인데
# 두 채널 값을 가지고 3개의 노드를 만드는 거라서 3x2가 된다

Parameter containing:
tensor([[-0.4604],
        [-0.7408],
        [ 0.8483]], requires_grad=True)
Parameter containing:
tensor([-0.0358, -0.6150, -0.9727], requires_grad=True)
Parameter containing:
tensor([[-0.0177, -0.2050,  0.4804]], requires_grad=True)
Parameter containing:
tensor([-0.4612], requires_grad=True)
tensor([-0.4962, -1.3558, -0.1243], grad_fn=<ViewBackward0>)
tensor([-0.2342], grad_fn=<ViewBackward0>)
tensor([-0.9347], grad_fn=<AddBackward0>)


In [10]:
# model=nn.Linear(1,1)
# x=torch.tensor([1.])
# y=model(x)
# print(model.weight)
# print(model.bias)
# y=x@model.weight+model.bias
# print(y)

Parameter containing:
tensor([[0.3393]], requires_grad=True)
Parameter containing:
tensor([0.0539], requires_grad=True)
tensor([0.3932], grad_fn=<AddBackward0>)


In [16]:
fc1=nn.Linear(1,3)
fc2=nn.Linear(3,1)

x=torch.tensor([1.])
# x=fc1(x)
# print(x)
# x=fc2(x)
# print(x)

model=nn.Sequential(fc1, fc2) # layer 풀칠
print(model(x))

tensor([-0.2602], grad_fn=<ViewBackward0>)


In [3]:
model=nn.Sequential(nn.Linear(2,5), # 여기는 채널, 채널
                    nn.Linear(5,10),
                    nn.Linear(10,3))
x=torch.randn(2)
print(x)
print(model(x))

x=torch.randn(1,2)
print(x)
print(model(x))

x=torch.randn(5,2) # 개x채 => 두 개의 채널 값(키, 몸무게)을 가지는 데이터(사람) 5개를 통과시킴
print(x)
print(model(x))
x=torch.randn(2,3,1,4,5,2)
print(model(x).shape)

tensor([ 0.2364, -1.3307])
tensor([-0.3698, -0.2154, -0.2660], grad_fn=<ViewBackward0>)
tensor([[-0.4524,  1.5182]])
tensor([[ 0.5647, -0.3625, -1.1626]], grad_fn=<AddmmBackward0>)
tensor([[ 0.0946, -1.5486],
        [ 1.2417,  1.0804],
        [ 0.5539, -0.8519],
        [ 0.3142,  0.7917],
        [ 0.2340, -1.8129]])
tensor([[-0.4441, -0.2303, -0.2220],
        [ 0.4440, -0.1261, -0.8237],
        [-0.2065, -0.1818, -0.3618],
        [ 0.3349, -0.2455, -0.8591],
        [-0.5297, -0.2065, -0.1293]], grad_fn=<AddmmBackward0>)
torch.Size([2, 3, 1, 4, 5, 3])


In [ ]:
class MyModel(nn.Module):
  def __init__(self):
    super().__init__()
  def forward(self,x):
    return x