In [1]:
import torch
from torch import nn

In [7]:
x=torch.tensor([1.])
model=nn.Linear(1,1) # 입력 node 1개, 출력 node 1개인 layer 만듦
print(model.weight) # 가중치
print(model.bias)
y=model(x)
print(y)
y=x@model.weight+model.bias # @:행렬연산, *:요소끼리 연산
print(y)

Parameter containing:
tensor([[-0.8210]], requires_grad=True)
Parameter containing:
tensor([0.9750], requires_grad=True)
tensor([0.1540], grad_fn=<ViewBackward0>)
tensor([0.1540], grad_fn=<AddBackward0>)


In [12]:
fc1=nn.Linear(1,3) # fully-connected
fc2=nn.Linear(3,1)

print(fc1.weight)
print(fc1.bias)
print(fc2.weight)
print(fc2.bias)

x=torch.tensor([1.])
x=fc1(x)
print(x)
x=fc2(x)
print(x)

y=(x@fc1.weight.T+fc1.bias)@fc2.weight.T+fc2.bias
print(y)

Parameter containing:
tensor([[-0.9441],
        [-0.2695],
        [ 0.1008]], requires_grad=True)
Parameter containing:
tensor([0.7469, 0.1731, 0.2788], requires_grad=True)
Parameter containing:
tensor([[-0.5305, -0.2250, -0.4728]], requires_grad=True)
Parameter containing:
tensor([-0.0886], requires_grad=True)
tensor([-0.1972, -0.0964,  0.3796], grad_fn=<ViewBackward0>)
tensor([-0.1417], grad_fn=<ViewBackward0>)
tensor([-0.7283], grad_fn=<AddBackward0>)
